# Generated by Django 2.2.3 on 2019-07-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmatic', '0002_image_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
