# Generated by Django 2.2.3 on 2019-07-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmatic', '0003_auto_20190722_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(max_length=850),
        ),
    ]
